# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateBayesFactorsRcpp <- function(zFilename, corFilename, priorType, priorValues, nSample, maxCausal, outputFile, exact, eps, useIdentityMatrix) {
    .Call('caviarbf_calculateBayesFactorsRcpp', PACKAGE = 'caviarbf', zFilename, corFilename, priorType, priorValues, nSample, maxCausal, outputFile, exact, eps, useIdentityMatrix)
}

