


# &&&&&&&&&&&&&&&&&& SPLICEAI &&&&&&&&&&&&&&&&&&&&
# GitHub: https://github.com/Illumina/SpliceAI
#
# quick_finemap()
# dat <- subset_DT

dataframe_2_vcf <- function(dat, 
                            samplename="GWAS",
                            reference_fasta="/pd-omics/tools/polyfun/reference_fasta/hg19.fa.gz",
                            output_vcf="./GWAS_converted.vcf"){
  # See: http://www.htslib.org/doc/1.2/bcftools.html
  # TSV conversion: 
  #   --tsv2vcf file
  # convert from TSV (tab-separated values) format (such as generated by 23andMe) to VCF. The input file fields can be tab- or space- delimited
  # -c, --columns list
  # comma-separated list of fields in the input file. In the current version, the fields CHROM, POS, ID, and AA are expected and can appear in arbitrary order, columns which should be ignored in the input file can be indicated by "-". The AA field lists alleles on the forward reference strand, for example "CC" or "CT" for diploid genotypes or "C" for haploid genotypes (sex chromosomes). Insertions and deletions are not supported yet, missing data can be indicated with "--".
  # -f, --fasta-ref file
  # reference sequence in fasta format
  # -s, --samples LIST
  # list of sample names. See Common Options
  # -S, --samples-file FILE
  # file of sample names. See Common Options
  
  # STEP 1
  ## Save df as tsv w/ ID,CHROM,POS,AA
  dat_mod <- dat %>% dplyr::mutate(AA = paste0(A1,A2), CHROM=paste0("chr",CHR)) %>% 
    dplyr::select(ID=SNP, CHROM, POS, AA)
  data.table::fwrite(x = dat_mod, file="./tmp.tsv",sep = "\t")
  
  # STEP 2
  ## Convert tsv to vcf with bcftools
  cmd <- paste("bcftools convert",
               "-c ID,CHROM,POS,AA",
               "-s", samplename,
               "-f",reference_fasta,
               "--tsv2vcf tmp.tsv",
               " -Oz", # options
               "-o",output_vcf)
  print(cmd)
  system(cmd) 
  
  # Remove tmps
  file.remove("./tmp.tsv") 
  
  return(output_vcf)
}




SPLICEAI.run <- function(vcf_path="./GWAS_converted.vcf",
                         output_path="spliceai_predictions.vcf",
                         # Ref fasta MUST be unzipped currently
                         reference_fasta="/pd-omics/tools/polyfun/reference_fasta/hg19.fa",
                         gene_annotation="./echolocatoR/tools/spliceAI/grch37.txt",
                         distance=50,
                         mask=0){
  # optional arguments:
  #   -h, --help     show this help message and exit
  #   -I [input]     path to the input VCF file, defaults to standard in
  #   -O [output]    path to the output VCF file, defaults to standard out
  #   -R reference   path to the reference genome fasta file
  #   -A annotation  "grch37" (GENCODE V24lift37 canonical annotation file in
  #                            package), "grch38" (GENCODE V24 canonical annotation file in
  #                                                package), or path to a similar custom gene annotation file
  #   -D [distance]  maximum distance between the variant and gained/lost splice
  #   site, defaults to 50
  #   -M [mask]      mask scores representing annotated acceptor/donor gain and
  #                  unannotated acceptor/donor loss, defaults to 0
  
  cmd <- paste("spliceai",
               "-I",vcf_path,
               "-O",output_path,
               "-R",reference_fasta,
               "-A",gene_annotation,
               "-D", distance,
               "-M",mask)
  print(cmd)
  system(cmd)
  
  
  
}
